name: qchem-qsharp-ds
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pip
  - numpy>=1.21.0
  - pandas>=1.3.0
  - matplotlib>=3.5.0
  - pyyaml>=6.0
  - scipy>=1.7.0
  - scikit-learn>=1.0.0
  - jupyterlab
  - lightgbm
  - shap
  - pip:
    - qsharp==0.28.0
    - qsharp-chemistry==0.28.0
    - pyscf
